#!/bin/bash

# This file is part of progstm32.
# 
# Copyright (C) 2018, Rishi Gupta. All rights reserved.
# 
# The progstm32 is free software; you can redistribute it and/or modify it 
# under the terms of the GNU Lesser General Public License as published 
# by the Free Software Foundation; either version 2.1 of the License, or 
# (at your option) any later version.
# 
# The progstm32 is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public 
# License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License 
# along with this library; if not, write to the Free Software Foundation,Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

cd "$(dirname '$0')"

if [[ $EUID -eq 0 ]]; then
	echo "$(tput setaf 1)Non root user required.$(tput sgr0)" 1>&2
	exit 1
fi

rm -rf INSTALL m4 configure Makefile.in depcomp config.guess config.sub >/dev/null 2>&1
rm -rf missing aclocal.m4 install-sh ltmain.sh config.h config.h.in compile >/dev/null 2>&1
rm -rf config.h.in~ configdata.pm autom4te.cache config.status config.log stamp-h1 >/dev/null 2>&1

mkdir m4

command -v libtoolize >/dev/null 2>&1
if  [ $? -ne 0 ]; then
    command -v libtool >/dev/null 2>&1
    if  [ $? -ne 0 ]; then
        echo "could not find libtool." 1>&2
        exit 1
    fi
fi

command -v pkg-config >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "pkg-config is required." 1>&2
    exit 1
fi

command -v autoreconf >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "autoconf and automake are required." 1>&2
    exit 1
fi

# sudo apt-get install autoconf-archive
autoreconf -vis -W all
status=$?
if [ $status -ne 0 ]; then
    echo "autoreconf exited with status $status" 1>&2
    exit 1
fi

echo "$(tput setaf 11)Bootstrapped successfully.$(tput sgr0)"

exit 0
