# Jars generated by make
progstm32app_jar=progstm32-app-1.0.jar
progstm32uart_jar=progstm32-uart-1.0.jar

# Jars taken from external projects
extlib_spcore=progstm32-sp-core-1.0.jar
extlib_sptty=progstm32-sp-tty-1.0.jar

# Decides color of text in console
if COLOR_SUPPORTED
define pry
@tput setaf 11
@echo $1
@tput sgr0
endef
else
define pry
@echo $1
endef
endif
