# Jars generated by make
progstm32app_jar=progstm32app.jar
progstm32uart_jar=progstm32uart.jar

# Jars taken from external projects
extlib_spcore=sp-core.jar
extlib_sptty=sp-tty.jar

# Decides color of text in console
if COLOR_SUPPORTED
define pry
	@tput setaf 11
	@echo $1
	@tput sgr0
endef
else
define pry
	@echo $1
	@tput sgr0
endef
endif
